version: '3.8'


services:
  toolkit:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - "./resources:/usr/bin/remote-toolkit/resources"
    working_dir: "/usr/bin/remote-toolkit"
    environment:
      - PATH=/usr/bin/remote-toolkit/bin
    entrypoint: /bin/bash
